[project]
name = "mmgp"
version = "3.7.6"
authors = [
  { name = "deepbeepmeep", email = "deepbeepmeep@yahoo.com" },
]
description = "Memory Management for the GPU Poor"
readme = "README.md"
requires-python = ">=3.10"
license-files = ["LICENSE.md"]
dependencies = [
  "torch >= 2.1.0",
  "optimum-quanto",
  "accelerate",
  "safetensors",
  "psutil"
]

